sudo: required
services:
  - docker

before_install:
  - docker build -t sacampb7/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sacampb7/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-742795906328"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_ACCESS_KEY"
